### ISSUE TITLE
Can't authorize with ST

### ISSUE THREAD

**Issue by tisfortorrey** [FlorianZ/hadashboard#22]
I have the following config variables filled in (and double and triple checked for typos), but I can't authorize no matter what I do. I keep getting Error 500.

 DASHING_AUTH_TOKEN
 DASHING_URI
 HEROKU_OAUTH_EMAIL
 HEROKU_OAUTH_ID
 HEROKU_OAUTH_SECRET
 HEROKU_POSTGRESQL_COBALT_URL 
 LANG
 RACK_ENV 
 SESSION_SECRET
 ST_CLIENT_ID
 ST_CLIENT_SECRET

**Comment by geman220** [comment]
Did you ever get this working?

**Comment by bmmiller** [comment]
Closing.
