### ISSUE TITLE
Dimming is unpredictable

### ISSUE THREAD

**Issue by kelchm** [FlorianZ/hadashboard#26]
I've noticed that dimming is pretty unpredictable if you are going up or down more than one level.  I'm new to working with the ST API, but I'm sure this is related to it's asynchronous design.

One easy workaround to this might be to simply use a slider instead of buttons.  Obviously the slider should only result in a command being issued after a mouseup / touchend event.

**Comment by bmmiller** [comment]
This was merged into the main branch.
