### ISSUE TITLE
Issues adding a PostgreSQL database

### ISSUE THREAD

**Issue by mkaplan1** [FlorianZ/hadashboard#32]
Florian,

Thanks for post your code / instructions. I'm getting an error adding the PostgreSQL database. I included my command screen to see where I might have made an error. 

Thanks in advance for your help.

C:\hadashboard>heroku addons:add heroku-postgresql:hobby-dev
Adding heroku-postgresql:hobby-dev on android-screen-display... done, v12 (free)

Attached as HEROKU_POSTGRESQL_ORANGE_URL
Database has been created and is available
 ! This database is empty. If upgrading, you can transfer
 ! data from another database with pgbackups:restore.
Use `heroku addons:docs heroku-postgresql` to view documentation.

C:\hadashboard>heroku addons:add heroku-postgresql:hobby-dev
Adding heroku-postgresql:hobby-dev on android-screen-display... done, v13 (free)

Attached as HEROKU_POSTGRESQL_MAROON_URL
Database has been created and is available
 ! This database is empty. If upgrading, you can transfer
 ! data from another database with pgbackups:restore.
Use `heroku addons:docs heroku-postgresql` to view documentation.

C:\hadashboard>heroku pg:wait

C:\hadashboard>git push heroku
warning: push.default is unset; its implicit value is changing in
Git 2.0 from 'matching' to 'simple'. To squelch this message
and maintain the current behavior after the default changes, use:

  git config --global push.default matching

To squelch this message and adopt the new behavior now, use:

  git config --global push.default simple

When push.default is set to 'matching', git will push local branches
to the remote branches that already exist with the same name.

In Git 2.0, Git will default to the more conservative 'simple'
behavior, which only pushes the current branch to the corresponding
remote branch that 'git pull' uses to update the current branch.

See 'git help config' and search for 'push.default' for further information.
(the 'simple' mode was introduced in Git 1.7.11. Use the similar mode
'current' instead of 'simple' if you sometimes use older versions of Git)

No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
Everything up-to-date

C:\hadashboard>git config --global push.default matching

C:\hadashboard>git push heroku
No refs in common and none specified; doing nothing.
Perhaps you should specify a branch such as 'master'.
Everything up-to-date

C:\hadashboard>

**Comment by FlorianZ** [comment]
Looks like the database was created successfully, and the real issue is that the master branch does not yet exist on the heroku remote.

Instead of `git push heroku`, try running `git push heroku master`.

**Comment by mkaplan1** [comment]
That appeared to work. 

Thanks again. 

Mark Kaplan

**Comment by mkaplan1** [comment]
Florian,

 

I’m getting this error when authorizing SmartThings. I’m getting a dashboard, but I don’t think they’re tied to my devices.

 

How do I check that?

 

Thanks,

 

Mark

**Comment by FlorianZ** [comment]
What's the error you're getting?

To set up your dashboard you will need to modify the `dashboards/main.erb` file to arrange the widgets for your specific devices. The app does not yet automatically discover devices to map them to specific widgets. Check out the section **Changing Widgets** in the instructions, as well as study the `dashboards/main.erb` file for some examples!

**Comment by mkaplan1** [comment]
Hi FlorianZ,

 

My dashboard doesn’t seem to be communicating with my devices. It seem to authorize just fine.  I edited my main.erb file (see example) and can see my changes to the titles of 2 widgets, but they don’t respond to or make changes to my devices. 

 

Am I using the correct “data-device=” name?

 

Where does the data-view type of widget come from?

 

 

 

 

 

 

 

 

 

 

 

 

<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">

      <div data-id="exteriorswitch" data-view="Stswitch" data-title="Front Door" data-device="Front Door Lights"></div>

    </li>

 

 

<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">

     <div data-id="presence1" data-view="Stpresence" data-title="Mark" data-device="Mark's iPhone"></div>

    </li>

 

 

 

cid:image001.png@01D03558.39504360

 

cid:image002.png@01D03558.39504360

 

cid:image004.png@01D03559.615694D0

 

cid:image003.png@01D03559.C2E42F00

 

 

 

 

Last thing is do I need to fix this error about webrick? 

 

 

cid:image006.png@01D0355B.B38B6EE0

 

 

 

Thanks again,

 

Mark

**Comment by FlorianZ** [comment]
Hey Mark. Your images don't come through if you reply to the github issue via email.

As for the *data-device* property: This should be set to the device label, exactly as you see it in the check marked list, when you authorize with SmartThins.

The *data-view* property is the type of the widget. If you want to control a switch this would be *Stswitch*. You can see which widgets are available by peeking in the `hadashboard/widgets` folder.

Not sure about the webrick error. There is no way for me to see the images you attached.
