### ISSUE TITLE
Switches that change state quickly never update status

### ISSUE THREAD

**Issue by rogersmj** [FlorianZ/hadashboard#33]
Summary: I have a number of virtual switches that, when activated to their "on" state, quickly revert back to "off" in SmartThings after triggering the things they're supposed to trigger (this is by design). However, in HAD they continue to show as "on" on my dashboard. 

This has the effect of forcing me to sometimes double-tap tiles in HAD in order to activate these virtual switches. If I have previously activated the switch, HAD shows it's "on" even though in ST it's "off". I have to tap it once to make it "off" in HAD, then tap it again to trigger the commands I want to run in SmartThings.

More background: I setup a bunch of virtual switch devices in the SmartThings IDE and then installed instances of an app called Virtual Switch Control Lights, and use this combination to effectively create lighting scenes. The way Virtual Switch Control Lights (VCSL) works is to automatically turn off it's "listener" virtual switch as soon as it runs all other lighting commands you associated with it. This is by design, and is analogous to how lighting scenes work in other home control platforms. It is this virtual switch that HAD thinks remains on when I toggle it from the dashboard, even though it remains off.

I looked at the Stswitch widget code but I'm not yet familiar enough with Dashing or the associated libraries to figure this out. I think the best solution might be to have the HAD widget request a status on a switch 10 seconds after the widget is tapped.

**Comment by bmmiller** [comment]
Things should always reflect 1:1 what is shown in ST.  This sounds like this was an update in general problem but given its age I'm just going to close it for now.  Reopen if you're still having this issue.
