### ISSUE TITLE
License to use

### ISSUE THREAD

**Issue by vargascyntiam** [FlorianZ/hadashboard#37]
Hi, 

I was wondering what are the limitations of using this implementation. I downloaded it and made some modifications, I won't use it for a commercial application but still was wondering if there is something that I need to take into account when using it

**Comment by FlorianZ** [comment]
Hi Cyntia.

My software is based on Dashing, which is distributed under the MIT
license. You are free to modify and reuse hadashboard! Let me know if there
is anything specific that you are worried about.

Hope that helps.

Florian

**Comment by timh5** [comment]
@FlorianZ  - Hi, can you please contact me? I wanted to possibly hire you for consulting or small development. timhon@gmail.com

**Comment by timh5** [comment]
^^ please delete above comment after you send email.
