### ISSUE TITLE
Stswitch not working

### ISSUE THREAD

**Issue by gmunson** [FlorianZ/hadashboard#38]
First, thanks so much for making such an unbelievably useful application.  I'm VERY new at this, but I've been able to get the HADashboard up and running.  I was able to authorize devices, and get the dashboard to lock and unlock a door.  However, I can't get any of my light switches to work.  The widget icon changes momentarily and then reverts to "off."  If it helps, the label on the widget always has quotation marks around it for the switches, even though it does not do that for the (functioning) door lock.  Any ideas?

Thanks in advance

**Comment by russrimm** [comment]
Make sure your "data-device" value is equal to the "display name" of the device on the Devices list when you look at your https://graph.api.smartthings.com/device/list

**Comment by FlorianZ** [comment]
Sorry for the late reply. What @russrimm said seems most likely. Make sure the device name you specify in your layout matches the device label in SmartThings, including whitespace and capitalization.

**Comment by gmunson** [comment]
I really appreciate the advice.  In the SmartThings API, I'm using the label that appears in the "Display Name" column in the Device List.  Is that correct?  For instance, one of them is "Family Room".  
<img width="647" alt="screen shot 2015-12-22 at 9 27 38 am" src="https://cloud.githubusercontent.com/assets/11179145/11957207/4c54dc28-a88e-11e5-89e4-b2b33bac3e29.png">

**Comment by russrimm** [comment]
That would be it.  Data-Device = the Display Name label. Example: I have one with Label "Large Christmas Tree" on the smartthings device list.  My xml is as follows:
      <div data-id="bigtree" data-view="Stswitch" data-icon="tree" data-title="Large Xmas Tree" data-device="Large Christmas Tree"></div>

**Comment by gmunson** [comment]
Here's an example of one I have that isn't working:

<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id=“downhall” data-view="Stswitch" data-title=“Downstairs Hallway“ data-device=“Downstairs Hallway”></div>
    </li>

The pertinent section of main.erb reads as follows:
<li data-row="1" data-col="1" data-sizex="1" data-sizey="1">
      <div data-id=“downhall” data-view="Stswitch" data-title=“Downstairs Hallway“ data-device=“Downstairs Hallway”></div>
</li>

**Comment by bmmiller** [comment]
The context highlighting a hint here I think.  It almost looks like different double quotes were used.  Maybe try typing it out fresh again?  I'd expect "Downstairs Hallway" to all be green in both instances.

**Comment by gmunson** [comment]
You. Rock.  Problem solved!  Thanks so much for taking the time to help a total neophyte.
