### ISSUE TITLE
Unable to complete authorisation

### ISSUE THREAD

**Issue by dws987** [FlorianZ/hadashboard#40]
Hi,

I hope you can help. I have followed your instructions and was successful up to the stage:
_"After clicking Authorize you should be redirected back to the default dashboard, and you should now have access to your things"._

So I have installed everything as per instructions, navigate to http://*my-app-name*.herokuapps.com, and granted the hadashboard app access to your Heroku account. - DONE successfully.

Then I access http://*my-app-name*.herokuapps.com/smartthings/authorize, get a list of my Smartthings 'things' (all listed). I then select a single item (as a test) and click the Authorize button. But instead of returning to the sample dashboard - I get an "Internal System Error" on firefox (which is basically a HTTP 500). The URL on this error page is: http://*my-app-name*.herokuapp.com/smartthings/oauth/callback?code=iss8nY
So it looks like it is trying to pass a code back, which is being rejected.

I have checked (several times) all the 'config' settings for the various required variables.
I have checked these via heroku web client, and by: heroku config.
I delete the SMARTAPP and recreated
I have (twice) delete the SMARTAPP and heroku database (so basically started from scratch with an install).

None of the above seem to resolve the issue. Any clues where to look for this issue resolution ?

**Comment by dws987** [comment]
Hi

Ok, I fixed the problem. I know know if this is because I am based in the UK, but ...
In your file: lib/stapp.rb
I change the routine getEndpoint(token)
from:
response.parsed()[0]['url']    <---- access URL
to:
response.parsed()[0]['uri']    <----- access URI

This fixed the authentication error
Thanks

**Comment by dws987** [comment]
Great dashboard :)

**Comment by FlorianZ** [comment]
Sorry for the late reply. Glad you figured it out, though! Have fun with it.
