### ISSUE TITLE
An error occurred while installing eventmachine (1.0.3), and Bundler cannot.

### ISSUE THREAD

**Issue by codeBearing** [FlorianZ/hadashboard#41]
I am getting the following compile when trying to push hadashboard to heroku.

> An error occurred while installing eventmachine (1.0.3), and Bundler cannot.

I have done some research saying it needs to be changed to 1.0.7 in the  Gemfile.lock however when I change it doesn't seem to change to the error.

Any help would be appreciated.

Stack trace from heroku:
-----> Ruby app detected
-----> Compiling Ruby/Rack
-----> Using Ruby version: ruby-2.2.4
-----> Installing dependencies using bundler 1.9.7
       Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
       Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Installing addressable 2.3.6
       Installing backports 3.6.1
       Installing execjs 2.0.2
       Installing coffee-script-source 1.8.0
       Installing daemons 1.1.9
       Installing rack 1.5.2
       Installing bcrypt 3.1.7
       Installing thread_safe 0.3.4
       Installing sass 3.2.19
       Installing tilt 1.4.1
       Installing multi_json 1.10.1
       Installing hike 1.2.3
       Installing thor 0.18.1
       Using json 1.8.1
       Installing fastercsv 1.5.5
       Installing json_pure 1.8.1
       Installing stringex 1.5.1
       Installing uuidtools 2.1.5
       Installing multipart-post 2.0.0
       Installing hashie 3.3.1
       Installing jwt 1.0.0
       Installing multi_xml 0.5.5
       Installing oa-core 0.3.2
       Using bundler 1.9.7
       Installing dm-core 1.2.1
       Installing ruby-openid 2.5.0
       Installing coffee-script 2.2.0
       Installing data_objects 0.10.14
       Installing rack-test 0.6.2
       Installing rack-protection 1.5.3
       Installing bcrypt-ruby 3.1.5
       Installing tzinfo 1.2.2
       Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
       /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160213-314-h9lpwz.rb extconf.rb
       checking for rb_trap_immediate in ruby.h,rubysig.h... no
       checking for rb_thread_blocking_region()... no
       checking for inotify_init() in sys/inotify.h... yes
       checking for writev() in sys/uio.h... yes
       checking for rb_wait_for_single_fd()... yes
       checking for rb_enable_interrupt()... no
       checking for rb_time_new()... yes
       checking for sys/event.h... no
       checking for epoll_create() in sys/epoll.h... yes
       creating Makefile
       make "DESTDIR=" clean
       make "DESTDIR="
       compiling kb.cpp
       compiling rubymain.cpp
       compiling em.cpp
       em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
       em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       em.cpp: In member function ‘int SelectData_t::_Select()’:
       em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
       return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
       ^
       em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
       em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
       EmSelect (0, NULL, NULL, NULL, &tv);
       ^
       make: **\* [em.o] Error 1
       make failed, exit code 2
       Gem files will remain installed in /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
       Results logged to /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
       Installing sprockets 2.10.1
       Installing faraday 0.9.0
       Installing omniauth 1.2.2
       Installing dm-aggregates 1.2.0
       Installing dm-constraints 1.2.0
       Installing dm-migrations 1.2.0
       Installing dm-serializer 1.2.2
       Installing dm-timestamps 1.2.0
       Installing dm-transactions 1.2.0
       Installing dm-validations 1.2.0
       Installing rack-openid 1.3.1
       Installing ruby-openid-apps-discovery 1.2.0
       Installing dm-do-adapter 1.2.0
       Installing sinatra 1.4.5
       Installing dm-types 1.2.2
       Installing rufus-scheduler 2.0.24
       Installing do_postgres 0.10.14
       An error occurred while installing eventmachine (1.0.3), and Bundler cannot
       continue.
       Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
       Bundler Output: Fetching gem metadata from https://rubygems.org/.........
       Fetching version metadata from https://rubygems.org/...
       Fetching dependency metadata from https://rubygems.org/..
       Installing addressable 2.3.6
       Installing backports 3.6.1
       Installing execjs 2.0.2
       Installing coffee-script-source 1.8.0
       Installing daemons 1.1.9
       Installing rack 1.5.2
       Installing bcrypt 3.1.7
       Installing thread_safe 0.3.4
       Installing sass 3.2.19
       Installing tilt 1.4.1
       Installing multi_json 1.10.1
       Installing hike 1.2.3
       Installing thor 0.18.1
       Using json 1.8.1
       Installing fastercsv 1.5.5
       Installing json_pure 1.8.1
       Installing stringex 1.5.1
       Installing uuidtools 2.1.5
       Installing multipart-post 2.0.0
       Installing hashie 3.3.1
       Installing jwt 1.0.0
       Installing multi_xml 0.5.5
       Installing oa-core 0.3.2
       Using bundler 1.9.7
       Installing dm-core 1.2.1
       Installing ruby-openid 2.5.0
       Installing coffee-script 2.2.0
       Installing data_objects 0.10.14
       Installing rack-test 0.6.2
       Installing rack-protection 1.5.3
       Installing bcrypt-ruby 3.1.5
       Installing tzinfo 1.2.2

```
   Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

   /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/ruby-2.2.4/bin/ruby -r ./siteconf20160213-314-h9lpwz.rb extconf.rb
   checking for rb_trap_immediate in ruby.h,rubysig.h... no
   checking for rb_thread_blocking_region()... no
   checking for inotify_init() in sys/inotify.h... yes
   checking for writev() in sys/uio.h... yes
   checking for rb_wait_for_single_fd()... yes
   checking for rb_enable_interrupt()... no
   checking for rb_time_new()... yes
   checking for sys/event.h... no
   checking for epoll_create() in sys/epoll.h... yes
   creating Makefile

   make "DESTDIR=" clean

   make "DESTDIR="
   compiling kb.cpp
   compiling rubymain.cpp
   compiling em.cpp
   em.cpp: In member function ‘void EventMachine_t::_RunEpollOnce()’:
   em.cpp:574:37: error: ‘rb_thread_select’ was not declared in this scope
   EmSelect (0, NULL, NULL, NULL, &tv);
   ^
   em.cpp: In member function ‘int SelectData_t::_Select()’:
   em.cpp:827:67: error: ‘rb_thread_select’ was not declared in this scope
   return EmSelect (maxsocket+1, &fdreads, &fdwrites, &fderrors, &tv);
   ^
   em.cpp: In member function ‘void EventMachine_t::_RunSelectOnce()’:
   em.cpp:946:40: error: ‘rb_thread_select’ was not declared in this scope
   EmSelect (0, NULL, NULL, NULL, &tv);
   ^
   make: *** [em.o] Error 1

   make failed, exit code 2

   Gem files will remain installed in /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/bundle/ruby/2.2.0/gems/eventmachine-1.0.3 for inspection.
   Results logged to /tmp/build_e1db61904b27941e800b08c46ba8d678/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/eventmachine-1.0.3/gem_make.out
   Installing sprockets 2.10.1
   Installing faraday 0.9.0
   Installing omniauth 1.2.2
   Installing dm-aggregates 1.2.0
   Installing dm-constraints 1.2.0
   Installing dm-migrations 1.2.0
   Installing dm-serializer 1.2.2
   Installing dm-timestamps 1.2.0
   Installing dm-transactions 1.2.0
   Installing dm-validations 1.2.0
   Installing rack-openid 1.3.1
   Installing ruby-openid-apps-discovery 1.2.0
   Installing dm-do-adapter 1.2.0
   Installing sinatra 1.4.5
   Installing dm-types 1.2.2
   Installing rufus-scheduler 2.0.24
   Installing do_postgres 0.10.14
   An error occurred while installing eventmachine (1.0.3), and Bundler cannot
   continue.
   Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.
```

 !
 !     Failed to install gems via Bundler.
 !
 !     Push rejected, failed to compile Ruby app

**Comment by Praveen-Invoscape** [comment]
I am also have the same issue @codeBearing , do you know how to solve it?????????

**Comment by bmmiller** [comment]
All of these sorts of issues should be fixed with the latest code.
