### ISSUE TITLE
Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES - bcrypt-ruby

### ISSUE THREAD

**Issue by chrisnicholls** [FlorianZ/hadashboard#44]
When I followed the instructions and got to the 'git push heroku' step, I got the following error. I was able to resolve by running bundle update and then pushing. I'm submitting a PR for the updated Gemfile.lock file. I'm not a ruby developer so I don't know if this is the proper solution but it worked for me!

remote:        Your Gemfile.lock is corrupt. The following gem is missing from the DEPENDENCIES
remote:        section: 'bcrypt-ruby'
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:
remote:  !     Push rejected, failed to compile Ruby app

**Comment by Adam1901** [comment]
I too am having the same issue.

Sorry to ask but you could you put exactly what you did. 

I'm still learning GIT (I have been an SVN) guy and have no experience with ruby or any web dev stuff really.

Thanks
Adam

**Comment by bmmiller** [comment]
@Adam1901 I am looking into this, trying to recreate as I didn't have this issue.

**Comment by bmmiller** [comment]
It won't go in the main repo until FlorianZ clears it, but go here to view the 3 files that I changed/added:

https://github.com/FlorianZ/hadashboard/pull/46/files

The Gemfile.lock is a complete copy of what @chrisnicholls did.  I need to spend some more time on it to get rid of the warning, but adding the Procfile removed a different warning message.

**Comment by RGSal** [comment]
I'm getting the same error as chrisnicholls. Is there a way to get past this? Your help will be greatly appreciated

**Comment by bmmiller** [comment]
@RGSal Did you try the link in my last post?

**Comment by RGSal** [comment]
Thanks for the Reply. Yes I did, unfortunately, the error messages didn´t go away. I ended up using Smart Tiles

**Comment by bmmiller** [comment]
@RGSal That should have been all that was necessary.  Just double checked it on my end and still good.

**Comment by shadowro2007** [comment]
no luck for me, even with the fixes from here:
https://github.com/FlorianZ/hadashboard/pull/46/files

using:
heroku/toolbelt/3.43.16 (i386-mingw32) ruby/2.1.7
heroku-cli/5.6.8-9647e01 (windows-386) go1.7.4
=== Installed Plugins
heroku-cli-oauth@2.0.4

any idea?
thanks in advance!

**Comment by ciaranmahoney** [comment]
@shadowro2007 I was getting the same error. I updated my Ruby version to 2.3.0, then made the changes to the Gemfile and Gemfile.lock. It may sound silly, but I forgot to commit for a while and was wondering why it was still saying `Using Ruby version: ruby-2.2.4` when I had Ruby 2.3.0 in the Gemfile. So double check you've committed your Gemfile changes too :)

**Comment by bmmiller** [comment]
I would definitely look into confirming that you're compiling with the correct Ruby version as @ciaranmahoney said.

**Comment by NiviJah** [comment]
Hi Guys,
Still having this issue, I wonder if this is something new or just never been fixed

**Comment by phae** [comment]
Just FYI that i was just rebuilding my dash and hit the same issue, and followed the file changes @bmmiller put in a PR and it sorted it for me. 

As an aside, I updated my stack to Cedar-14 - not sure if that helped. https://devcenter.heroku.com/articles/cedar-14-stack#upgrading-the-production-app-to-cedar-14

**Comment by bmmiller** [comment]
Yeah, I hadn't attempted Cedar-14 yet but you'll need to at least use my fork to get passed the errors mentioned.

**Comment by bmmiller** [comment]
The main hadashboard now has the changes to fix all of this merged into them.
