### ISSUE TITLE
Unable to auth with ST

### ISSUE THREAD

**Issue by geman220** [FlorianZ/hadashboard#47]
I've followed the guide and repeated the steps 4 times.  Everytime I'm ending up with:

```
Error
500: Internal Server Error
URI
/oauth/authorize
Reference Id
9d377c09-5988-4b26-856d-0482e74b6d83
Date
Sun Apr 24 09:24:28 UTC 2016
```

I have my auth set correctly in:

```
heroku config:set \
  DASHING_AUTH_TOKEN=RANDOM UUID HERE \
  DASHING_URI=http://myapp-somestuff-3333.herokuapp.com \
  HEROKU_OAUTH_EMAIL=myheroku@email.com \
  HEROKU_OAUTH_ID=UUID from heroku clients:create -s "hadashboard" https://your-app-name.herokuapp.com/auth/heroku/callback \
  HEROKU_OAUTH_SECRET=UUID from heroku clients:create -s "hadashboard" https://your-app-name.herokuapp.com/auth/heroku/callback \
  SESSION_SECRET=A DIFFERENT RANDOM UUID HERE \
  ST_CLIENT_ID=MT ST UUID \
  ST_CLIENT_SECRET=MY ST SECRET UUID
```

I open my web browser and go to https://my-app-123.herokuapp.com/smartthings/authorize

Which redirects to: https://graph.api.smartthings.com/oauth/confirm_access?response_type=code&scope=app&redirect_uri=http%3A%2F%2Fmy-app-123.herokuapp.com%2Fsmartthings%2Foauth%2Fcallback&client_id=ST CLIENT ID 

I select 'Home' as a location and select all of the lights / sensors, and select 'Authorize', and then I receive this message.

```
Oh No! Something Went Wrong!
Error
500: Internal Server Error
URI
/oauth/authorize
Reference Id
9c20bdd8-1309-4290-be21-ac9b81634d0b
Date
Sun Apr 24 09:40:01 UTC 2016
```

Sometimes after attempting to auth I get re-directed to:
http://my-app-123.herokuapp.com/smartthings/oauth/callback?code=xbAOmK 
But I still have 
`Internal Server Error`
Any help would be greatly appreciated.

**Comment by mckeem** [comment]
Are you in Europe by any chance?

I was having this issue, and because I am in the UK I had to change the Graph API url. 

My Graph API URL is https://graph-eu01-euwest1.api.smartthings.com. You will need to double check what yours is first. 

Open up /lib/stapp.rb and change line 11 from;
`site: 'https://graph-eu01-euwest1.api.smartthings.com',`

to 
`site: 'https://graph-eu01-euwest1.api.smartthings.com'`

Commit your changes and push them up to Heroku. Now try auth'ing with SmartThings again

**Comment by bmmiller** [comment]
@geman220 Are you still having issues?

**Comment by patchedsoul** [comment]
ST is undergoing a SSO consolidation. The `site: 'https://graph.api.smartthings.com',` will most likely need to be edited for any newcomers

**Comment by bmmiller** [comment]
Thanks @patchedsoul, I'll keep an eye on this.  I'd imagine if ST complete cuts off the legacy URL, many integrations will break so it'll either take them a long time to do this or they never will.

**Comment by bsstaaden** [comment]
FYI, I got the internal server error on the oauth/callback as well. Issue was resolved by going into stapp.rb and inside getEndpoint(token), I changed: 
response.parsed()[0]['url'] 
To:
response.parsed()[0]['uri']

Suddenly, everything connected up and no more internal errors after auth.

**Comment by bmmiller** [comment]
That's odd that would be required. 'url' still works for me.

**Comment by bsstaaden** [comment]
Could it be an issue of windows vs linux, or a different version of Ruby?

**Comment by bmmiller** [comment]
It shouldn't matter what you are working in.  It matters what it is running in, which is Heroku.  Also, "response.parsed" is quite literally what gets parsed from a response.  Environment or Ruby version should be irrelevant.

I'd have to re-setup something from scratch to see if this piece just gets cached once and then isn't needed again.

**Comment by ckeehan** [comment]
I had this issue too. I'm in the US, but @mckeem's solution worked for me using the URL:
`site: 'https://graph-na04-useast2.api.smartthings.com'`

Committed and pushed the changes. Worked like a charm!

**Comment by vinaykapadia** [comment]
Had the same problem, I changed mine to https://graph-na04-useast2.api.smartthings.com as well and it works great. Thanks!

**Comment by bmmiller** [comment]
I'm not sure why this is necessary. I rebuilt mine from scratch last night and https://graph-na04-useast2.api.smartthings.com did **_NOT_** work.  

https://graph.api.smartthings.com still works.  Has to be something on your accounts being different.

**Comment by vinaykapadia** [comment]
Could be. I do know that when I go to https://graph.api.smartthings.com it doesn't show me anything under the Hubs, Smartapps, or Devices headers. I have to click Locations, then select anything from there, which redirects me to the https://graph-na04-useast2.api.smartthings.com domain, after which I can click on the headers and it shows my stuff.

**Comment by bmmiller** [comment]
That's some interesting additional information.  My IDE is https://graph.api.smartthings.com and I can see everything just fine.  

Very likely the answer then.  

Just a quick heads up though, this main code still works but isn't being actively contributed to anymore.  Things have progressed a little further at my fork, https://github.com/bmmiller/hadashboard

I don't have the time to actively keep both up to speed and some things were added here that I don't want added in my fork so I can't just kill the fork and stay here.  If that makes sense...
