### ISSUE TITLE
Get widgets to work

### ISSUE THREAD

**Issue by ThirstyThursten** [FlorianZ/hadashboard#50]
Hello, 
I'm sorry if this isn't the right place for this..

I think I've missed something.. I have followed every step, got the visuals but I don't have any Domotica stuff yet.. So I'm trying to get the weather widget to work.. Do I need to do anything for that? I can't seem to find anything in the code that states my location or where it gets it's information..

And what do I have to configure in Smartthings? 'Cause i've got my new app but there ain't any devices or hubs.. Do I need a hub or how does this work? I feel as if I missed a step in that department.
I other words, how do I connect a widget to a device or information?

So I would be very grateful with some help! =)

Further more.. I just love your work here FlorianZ It looks amazing and I am very jealous of your skills! I hope I can get this to work someday, because the whole tablet wall mount idea was swirling in my head for a while and then I came across your amazing project here! =D

Thanks in advance
Greetings,
Thursten

**Comment by bmmiller** [comment]
What do you mean by Domotica stuff?

This app is for SmartThings integration only.  If you are trying to connect it to another service, this isn't going to work for you without major modifications.

**Comment by bmmiller** [comment]
Closing this as I don't think this is relevant and never heard a reply back.
