### ISSUE TITLE
Unable to Authorize with SmartThings

### ISSUE THREAD

**Issue by kerednai** [FlorianZ/hadashboard#52]
Hi,
When I get to step 6 - Authorize with SmartThings..
I select the relevant location but I cannot click Authorize. I get the error message:
Client is not associated with a SmartApp in location <my location>.

The client_id displayed is the same client_id that was given to my smart things application. What am I missing?

**Comment by bsstaaden** [comment]
Same issue. Noticed as well that the ST_CLIENT_ID is listed at the top of the SmartThings page, NOT the HEROKU_OAUTH_ID... not sure which it's supposed to be displaying, but it seems odd that it would be displaying the GUID of the app I'm calling rather than the one that made the call.

**Comment by bmmiller** [comment]
Thanks @bsstaaden for following up.  Going to close this.  If @kerednai still has the issue after attempting the same fix, reply back.
