### ISSUE TITLE
Dimmer not working on Firefox Quantum and Tablets/Smartphones

### ISSUE THREAD

**Issue by mekliches** [FlorianZ/hadashboard#53]
Any clue how to get it work, i use the device handler from julienbachmann and it has the capability switch leve, sot the stdimmer should work with that. it actually picks the right level, but changing the level on the dashboard doesn't do anything.

help would be much appreciated :)

**Comment by bmmiller** [comment]
Do me a favor and check on an actual computer in a modern browser.  There is a known bug on tablets/smartphones.

**Comment by mekliches** [comment]
sure, did on the latest firefox version. i can open or close the shades. and on initial load i can see it display the correct level, but trying to set level doesn't trigger any action, even on IDE live logging i don't see any action coming when trying to change the level of the sahdes.

**Comment by bmmiller** [comment]
It doesn't really matter what the device is as it's still the dimmer function.  I hadn't actually tried with the new Firefox Quantum yet but it does indeed not work there.  It DOES work in Chrome though, so I'm chalking this up to the known bug.

**Comment by mekliches** [comment]
you're absolutely right sir.
works like a charm on chrome :)

**Comment by bmmiller** [comment]
A fix for you is detailed here:
https://github.com/bmmiller/hadashboard/commit/5777c8ced6d5b90e7e77843d881e4b51fdd915ff

I reverted the widget back to the original +/- functionality.  I'm not actively maintaining the original source here so it might behoove you to move to my fork.

I recognize that individual steps might not be ideal for a shade pretending to be a dimmer for your particular case but the slider is causing too much havoc.
